### ISSUE TITLE
android.util.AndroidException: INSTRUMENTATION_FAILED: my.com.tngdigital.ewallet.uat.test/android.support.test.runner.AndroidJUnitRunner

### ISSUE THREAD

**Issue by yangdong125845** [Jay-Goo/JacocoTestHelper#5]
adb: failed to stat app/build/outputs/apk/androidTest/SANDGoogleplay/debug/*.apk: No such file or directory
android.util.AndroidException: INSTRUMENTATION_FAILED: my.com.tngdigital.ewallet.uat.test/android.support.test.runner.AndroidJUnitRunner
        at com.android.commands.am.Instrument.run(Instrument.java:421)
        at com.android.commands.am.Am.runInstrument(Am.java:187)
        at com.android.commands.am.Am.onRun(Am.java:80)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
adb: error: failed to stat remote object '/sdcard/my.com.tngdigital.ewallet.uat/coverage.ec': No such file or directory

**Comment by yangdong125845** [comment]
在多library下如何集成
